### ISSUE TITLE
Support write operation

### ISSUE THREAD

**Issue by hubjac1** [traviscrawford/spark-dynamodb#17]
Hi,

Write to dynamoDb is currently not supported. Would it be possible to add it?

Thanks,
Hub

**Comment by timchan-lumoslabs** [comment]
@hubjac1 What is your use case? Do you want to write a DataFrame directly into DynamoDB?

**Comment by hubjac1** [comment]
Hi @timchan-lumoslabs, 
My questions is naive because I'm not very familiar with Spark. 

I read a dataFrame from DynamoDb, I do update some columns then I'd like to write my changes to DynamoDb by chunck.

Regards

**Comment by igreenfield** [comment]
What the status of that? I also need the ability to write into dynamo DB

**Comment by traviscrawford** [comment]
At this time I don't have plans to add write support, but would be happy to review the change if someone is interested in adding support.
