### ISSUE TITLE
.dynamoDB not found ?

### ISSUE THREAD

**Issue by huanchh** [traviscrawford/spark-dynamodb#22]
trying to use the DataFrame API

val users = sqlContext.read.dynamodb("users")      

we are using java in our project, when trying the following
import com.github.traviscrawford.spark.dynamodb.*;
......
SQLContext sqlContext = new org.apache.spark.sql.SQLContext(spark.sparkContext());
sqlContext.read()

it seems .dynamodb() is not a defined method, is there something we are missing ?

**Comment by huanchh** [comment]
never mind, figured it out, from Java one calls 
import com.github.traviscrawford.spark.dynamodb.package$;
DataFrameReader reader = sqlContext.read().option("endpoint", "http://localhost:8000");
Dataset<Row> rows = package$.MODULE$.DynamoDBDataFrameReader(reader)

thanks

**Comment by MingweiSamuel** [comment]
can you close this then?
