### ISSUE TITLE
How do I set my AWS credentials?

### ISSUE THREAD

**Issue by mike-sayan** [traviscrawford/spark-dynamodb#26]
Hey, there's no examples for setting the configuration attributes. How do I set my own AWS credentials for the sqlContext? Thanks! 

Not really an issue in itself, but more documentation would be nice.

**Comment by traviscrawford** [comment]
By default, credentials work the standard way for the AWS SDK. Details are here:

http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default

I agree this could be explicitly documented. Any interest in sending a PR improving the docs? For users, you could update the README.md file. In the code, a comment could be added to https://github.com/traviscrawford/spark-dynamodb/blob/master/src/main/scala/com/github/traviscrawford/spark/dynamodb/BaseScanner.scala#L17

**Comment by bendrecm** [comment]
The documentation is not clear how to provide own credentials. What should be the value of option _aws_credentials_provider_ ? can you provide an example ?

**Comment by traviscrawford** [comment]
Most users should not need to set this value. If your site has a custom credentials provider, the value would be the full name of your custom credentials provider class.

See https://github.com/traviscrawford/spark-dynamodb/blob/master/src/main/scala/com/github/traviscrawford/spark/dynamodb/BaseScanner.scala for details.

**Comment by sanchitmishra** [comment]
Hey, I am running on EMR cluster and my DynamoDB table is in different aws account. I am passing  the assumed role in the credentials provider which is generating tokens in background which are valid for 1 hour. The tale I am reading from contains 45 millions which takes more than 1 hour for read. Is there any way I can bypass this?
