### ISSUE TITLE
filter_expression not working as expected.

### ISSUE THREAD

**Issue by sarojgharat** [traviscrawford/spark-dynamodb#32]
Hi, 

I have a DynamoDB table with offer_id as the hash key and created_on as the range key. Trying to execute the below scala program. The filter expression is somehow not working . It is showing me more records than expected. Am I doing something wrong here ?

import com.github.traviscrawford.spark.dynamodb._
val sqlContext = new org.apache.spark.sql.SQLContext(sc)

import org.apache.spark.sql._
import org.apache.spark.sql.types._
val schema = StructType(
  Seq(
    StructField("offer_id", StringType),
    StructField("created_on", StringType)
  )
)

val tblImpressionLog = sqlContext.read.option("filter_expression", "offer_id = 688").dynamodb("eu-central-1", "tblImpressionLog")

tblImpressionLog.show

**Comment by traviscrawford** [comment]
I just added a test for this exact case, and it's passing:
https://github.com/traviscrawford/spark-dynamodb/blob/master/src/test/scala/com/github/traviscrawford/spark/dynamodb/DynamoDBRelationIntegrationSpec.scala#L91

Can you share more details about the issue you're seeing?

**Comment by traviscrawford** [comment]
I merged this to master. Please let me know if you have any issues.
