### ISSUE TITLE
Using spark-dynamodb in unit tests

### ISSUE THREAD

**Issue by bendrecm** [traviscrawford/spark-dynamodb#37]
DynamoDB provides local instance http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html 

Is there a way to read dataframe from local dynamodb by providing endpoint and credentials ?

I tried following code but it throws exception ->

`val optDF = spark.sqlContext.read.option("endpoint","http://localhost:12000").dynamodb("tempTable")`

This throws error -
java.lang.RuntimeException: `com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Cannot do operations on a non-existent table (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: xxx-xxx)`

The table is created using AmazonDynamoDBClient connected to local server -> 
```
amazonDynamoDB = new AmazonDynamoDBClient(new BasicAWSCredentials("access", "secret"))
amazonDynamoDB.setEndpoint("http://localhost:" + port)
amazonDynamoDB.createTable(...
```

The table arn when printed is ->
`arn:aws:dynamodb:ddblocal:000000000000:table/tempTable`

**Comment by traviscrawford** [comment]
Interesting. Yes you can connect to the local instance and we do this in the unit tests so I’m confident it works. Can you try connecting with just the host:port of your local instance (without the http prefix)

**Comment by traviscrawford** [comment]
I take it back - it does look the http prefix is needed. Here’s how we connect in tests:

https://github.com/traviscrawford/spark-dynamodb/blob/master/src/test/scala/com/github/traviscrawford/spark/dynamodb/BaseIntegrationSpec.scala

Can you telnet to the port you think the server is running on to confirm it’s listening there?

**Comment by bendrecm** [comment]
Yes, the server is running at 12000 port and i am able to telnet it. Actually, i am initializing the server from the code itself since AWS provides that option ->
```
  def init(): Unit = {
    try {
      System.setProperty("sqlite4java.library.path", "native-libs")
      server = ServerRunner.createServerFromCommandLineArgs(Array[String]("-inMemory", "-port", port))
      server.start()
    } catch {
      case e: Exception => throw new RuntimeException(e)
    }
  }
```
Also, I think the spark-dynamodb is picking up local instance credentials by default, how to provide credentials to spark-dynamodb ? In this case, "access" and "secret". Will try this

**Comment by bendrecm** [comment]
I was able to get around this issue using "-sharedDb" flag provided by DynamoDBLocal. So closing this issue.
