### ISSUE TITLE
org.apache.spark.sql.AnalysisException: Table or view not found:

### ISSUE THREAD

**Issue by kurtmaile** [traviscrawford/spark-dynamodb#38]
Hi,

We have a number of DDb tables and I am Pocing this library to access some DDb table.  We actually use databricks as the platform.

Im doing a very simple query:

import com.github.traviscrawford.spark.dynamodb._
val data = sqlContext.sql(
  "select id from purchaseorderline_uk")

but get an error below

org.apache.spark.sql.AnalysisException: Table or view not found: purchaseorderline_uk; line 1 pos 15

The table absolutely exists and the job is assuming a role that gives it DDBFull rights.  I also have internet access via the Nat gateway so internet access if fine.

Totally stumped on this seemingly simple query to a table that exists.  Is there some configuration that is required that isnt documented (or that I just missed!).  Has anyone had this before?  

Im using the v0.11 (latest) that is in maven 

thanks!

**Comment by traviscrawford** [comment]
Looking at your example code, I think you need to load the data frame from your DynamoDB table and register as a temp table before you can query with SQL. Here's an example from the readme. Specifically, note the `sqlContext.read.dynamodb` part:

https://github.com/traviscrawford/spark-dynamodb#dataframe-usage

```
import com.github.traviscrawford.spark.dynamodb._

// Read a table in the default region.
val users = sqlContext.read.dynamodb("users")

// Or read a table from another region.
val users2 = sqlContext.read.dynamodb("us-west-2", "users")

// Query with SQL.
users.registerTempTable("users")
val data = sqlContext.sql("select username from users where username = 'tc'")
```

**Comment by kurtmaile** [comment]
Hi,

Thanks for this.  I actually had the code for reading the DDB table and storing as a temp table - just forgot to put it in the code in the post.

What i didnt have was the region param - this did the trick many thanks! :)

Do you know of anyone using this on databricks?  I assume given this library includes dependant AWS libraries I will need to build a version without these (given databricks provide AWS libraries by default having two sets on the classpath will be a source of issue.)

Anyhow - Im connected to DDB so many thanks awesome work :)

**Comment by traviscrawford** [comment]
Glad you got it working! What might make sense in your environment is
filtering out the AWS SDK dependency when depending on the spark-dynamodb
artifact (in your pom.xml or equivenant). That way you’ll use the AWS SDK
provided by Databricks.

If you run into issues I can bump the dependency version numbers and
publish a new release. There aren’t that many deps for this library, but
sometimes we do need to upgrade to the newer APIs.
