### ISSUE TITLE
Reader parses schema but returns no rows

### ISSUE THREAD

**Issue by fzqneo** [traviscrawford/spark-dynamodb#49]
The result of the first command suggests it connects to dynamodb and parses the schema. But there are no rows in the dataframe, while I'm sure the dynamodb table is not empty.

```
scala> val users = spark.sqlContext.read.dynamodb("ap-southeast-1", "user")
users: org.apache.spark.sql.DataFrame = [account_name: string, avatar: string ... 24 more fields]

scala> users.count()
res15: Long = 0
```

**Comment by protometa** [comment]
Damn, I'm just now running into this. Did you find any solution?

**Comment by protometa** [comment]
This seemed to be related to having a nested json format. If I used json that wasn't nested or left out the nested fields in my schema the records showed up. I was able to work around by reading as rdd and then reading the rdd with dataframe reader as json as suggested in #46

**Comment by PowerToThePeople111** [comment]
I got the same problem with this dynamodb exporter. This [one](https://github.com/audienceproject/spark-dynamodb) works fine though and also seems to have been updated more recently.

**Comment by fzqneo** [comment]
I switched to something else and didn't continue with the issue. Please refer to the comments above for possible solution.
