### ISSUE TITLE
How to use with Gradle in a project?

### ISSUE THREAD

**Issue by dyerw** [traviscrawford/spark-dynamodb#5]
What should I add to my build.gradle to import this? Is the artifact published anywhere? Sorry if this is obvious, I'm new to Java build tools and need to get this to work.

**Comment by traviscrawford** [comment]
I just filed https://issues.sonatype.org/browse/OSSRH-24019 requesting access to maven central.

**Comment by traviscrawford** [comment]
Hi @dyerw - can you try the installation instructions listed at:
https://github.com/traviscrawford/spark-dynamodb#installation

**Comment by dyerw** [comment]
@traviscrawford thank you for the quick fix!
