### ISSUE TITLE
Upgrade to be compatible with Spark 2.0.0

### ISSUE THREAD

**Issue by timchan-lumoslabs** [traviscrawford/spark-dynamodb#6]
I'd like to use this with Spark 2.0.0. Will this be happening any time soon?

**Comment by traviscrawford** [comment]
Eventually I would like to, though I'm waiting for a point release before upgrading Medium to 2.0. I'm totally open to a PR upgrading if you'd like to move faster.

Looking at https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala I think this might Just Work though it was a quick look on my phone. If you upgrade the spark dependency and rebuild do the tests pass?

**Comment by traviscrawford** [comment]
Fixed via #8 !!!
